from_latest_tag = true
tag_prefix = "v"
skip_ci = "[skip ci]"

post_bump_hooks = [
    "perl -i -pe 's/^(\\s*)<Version>.*<\\/Version>/$1<Version>{{version}}<\\/Version>/' sim6502/sim6502.csproj",
]

[changelog]
path = "CHANGELOG.md"

[commit_types]
feat = { changelog_title = "Features", bump_minor = true }
fix = { changelog_title = "Bug Fixes", bump_patch = true }
docs = { changelog_title = "Documentation", bump_patch = true }
chore = { changelog_title = "Chores", bump_patch = true }
