from_latest_tag = true
tag_prefix = "v"
skip_ci = "[CI SKIP]"

post_bump_hooks = [
    "sed -i 's|<Version>.*</Version>|<Version>{{version}}</Version>|' sim6502/sim6502.csproj",
    "sed -i 's|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>{{version}}.0</AssemblyVersion>|' sim6502/sim6502.csproj",
    "sed -i 's|<FileVersion>.*</FileVersion>|<FileVersion>{{version}}.0</FileVersion>|' sim6502/sim6502.csproj",
]

[changelog]
path = "CHANGELOG.md"

[commit_types]
feat = { changelog_title = "Features", bump_minor = true }
fix = { changelog_title = "Bug Fixes", bump_patch = true }
docs = { changelog_title = "Documentation", bump_patch = true }
chore = { changelog_title = "Chores", bump_patch = true }
